dataset: multiwiener
data:
  psf_crop: null
  psf_normalization: null
eval:
  batch_size: 1
  normalize: clip_max
baselines:
  wiener:
    name: wiener
    options: {psf_norm: max, psf_scale: 0.01, center_index: 4, gaussian_windows: 3, in_channels: 1, out_channels: 1}
  admm:
    name: admm
    options: {psf_norm: none, psf_scale: 0.00392156862745098, center_index: 4, iterations: 100, stacks: 1, trainable: true, in_channels: 1, out_channels: 1}
  unet:
    name: unet
    options: {psf_norm: none, psf_scale: 0.00392156862745098, implementation: shared, in_channels: 1, out_channels: 1}
  lensnet:
    name: lensnet
    options: {psf_norm: max, psf_scale: 1.0, center_index: 4, use_input_psf: true, in_channels: 1, out_channels: 1, ngf: 64}
  nafnet:
    name: nafnet
    options: {psf_norm: none, psf_scale: 0.00392156862745098, in_channels: 1, out_channels: 1}
  updn:
    name: updn
    options: {psf_norm: l2, psf_scale: 1.0, center_index: 4, depth: 10, mix_colors: false, in_channels: 1, out_channels: 1}
  mwdns:
    name: mwdns
    options: {psf_norm: max, psf_scale: 1.0, center_index: 4, in_channels: 1, out_channels: 1}
  multiwienernet:
    name: multiwienernet
    options: {psf_norm: max, psf_scale: 1.0, k: 9, psf_batch_dim: true, implementation: shared, in_channels: 1, out_channels: 1}
  modl:
    name: modl
    options: {psf_norm: max, psf_scale: 1.0, center_index: 4, iterations: 5, psf_in_channels: 1, three_dimensional: true, in_channels: 1, out_channels: 1}
  leadmmu:
    name: leadmmu
    eval: {normalize: max}
    options: {psf_norm: max, psf_scale: 1.0, center_index: 4, iterations: 5, height: 224, width: 320, in_channels: 1, out_channels: 1}
  deeplir:
    name: deeplir
    options: {psf_norm: max, psf_scale: 1.0, center_index: 4, iterations: 5, dim: 32, dim_mults: [1, 2, 4, 8], in_channels: 1, out_channels: 1}
